server:
  port: 8082

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

      inventoryService:
        slidingWindowSize: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      inventoryRetry:
        maxAttempts: 3
        waitDuration: 2s

      productRetry:
        maxAttempts: 3
        waitDuration: 2s

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9412/api/v2/spans
